services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url-shortener-db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    volumes:
      - .:/app  # for the mounting of the source code
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/url-shortener-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"

volumes:
  postgres-data:
