services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url-shortener-db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
#    volumes:ITfM7v6d7C
#      - .:/app  # for the mounting of the source code
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/url-shortener-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    develop:
      watch:
        - path: ./src
          action: sync+restart
          target: /app/src
        - path: ./pom.xml
          action: rebuild
        - path: ./mvnw
          action: rebuild
        - path: ./.mvn
          action: rebuild

volumes:
  postgres-data:
